version: "3.9"


services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  ports:
   - "443:443"
     #volumes:
    #   - wp:/var/www/html
    # networks:
    # - app-network
  restart: unless-stopped
