version: "3.9"
 
services:
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb
  restart: always
    #  volumes:
    #   - db:/var/lib/mysql
  networks:
   - inception
  env_file:
   - .env

 wordpress:
  depends_on:
   - mariadb
  container_name: wordpress
  build: ./requirements/wordpress
  restart: always
    #  volumes:
    #   - wp:/var/www/html
  networks:
   - inception
  env_file:
   - .env

 nginx:
  depends_on:
   - wordpress
  container_name: nginx
  build: ./requirements/nginx
  restart: always
    #  volumes:
    #   - wp:/var/www/html
  networks:
   - inception
  ports:
   - "443:443"
  env_file:
   - .env

     #volumes:
     # wp:
     #  driver: local
     #  name: wp
     #  driver_opts:
     #   type: none
     #   o: bind
     #   device: /home/hportife/data/wordpress
     # db:
     #  driver: local
     #  name: db
     #  driver_opts:
     #   type: none
     #   o: bind
     #   device: /home/hportife/data/mariadb

networks:
 inception:
  name: inception
  driver: bridge
